ban dosbin, heresbin and newsbin on cross
we merge sbin into bin now

Change-Id: I40f01ec0a003930920be3854cf9d1592997a8e31

diff --git a/paludis/repositories/e/ebuild/utils/exheres-0/banned_in_eapi_exheres-0 b/paludis/repositories/e/ebuild/utils/exheres-0/banned_in_eapi_exheres-0
--- a/paludis/repositories/e/ebuild/utils/exheres-0/banned_in_eapi_exheres-0
+++ b/paludis/repositories/e/ebuild/utils/exheres-0/banned_in_eapi_exheres-0
@@ -17,12 +17,17 @@
 # this program; if not, write to the Free Software Foundation, Inc., 59 Temple
 # Place, Suite 330, Boston, MA  02111-1307  USA
 
-COLOUR_RED=$'\e[31;01m'
-COLOUR_NORMAL=$'\e[0m'
+die_because_banned_in_eapi_exheres-0() {
+    COLOUR_RED=$'\e[31;01m'
+    COLOUR_NORMAL=$'\e[0m'
 
-echo "${COLOUR_RED}!!! Ebuild bug: '$(basename ${0} )' banned in EAPI exheres-0${COLOUR_NORMAL}"
-echo "$(basename ${0} ): making ebuild PID ${EBUILD_KILL_PID} exit with error" 1>&2
-kill -s SIGUSR1 "${EBUILD_KILL_PID}"
+    echo "${COLOUR_RED}!!! Exheres bug: '$(basename ${0} )' banned in EAPI exheres-0${COLOUR_NORMAL}"
+    echo "$(basename ${0} ): making exheres PID ${EBUILD_KILL_PID} exit with error" 1>&2
+    kill -s SIGUSR1 "${EBUILD_KILL_PID}"
 
-exit 123
+    exit 123
+}
+
+# die if called directly, but not if sourced
+return 2> /dev/null || die_because_banned_in_eapi_exheres-0
 
