D -> IMAGE for exheres.

diff --git a/paludis/repositories/e/ebuild/utils/dohard b/paludis/repositories/e/ebuild/utils/dohard
--- a/paludis/repositories/e/ebuild/utils/dohard
+++ b/paludis/repositories/e/ebuild/utils/dohard
@@ -21,8 +21,8 @@
 # this program; if not, write to the Free Software Foundation, Inc., 59 Temple
 # Place, Suite 330, Boston, MA  02111-1307  USA
 
-if [[ ! -d ${D} ]]; then
-    echo "${0}: \${D} not valid; aborting" >&2
+if [[ ! -d ${!PALUDIS_IMAGE_DIR_VAR} ]]; then
+    echo "${0}: \${${PALUDIS_IMAGE_DIR_VAR}} not valid; aborting" >&2
     exit 247
 fi
 
@@ -31,4 +31,4 @@ if [[ ${#} -ne 2 ]]; then
     exit 1
 fi
 
-ln -f "${D}${1}" "${D}${2}"
+ln -f "${!PALUDIS_IMAGE_DIR_VAR}${1}" "${!PALUDIS_IMAGE_DIR_VAR}${2}"
diff --git a/paludis/repositories/e/ebuild/utils/dohtml b/paludis/repositories/e/ebuild/utils/dohtml
--- a/paludis/repositories/e/ebuild/utils/dohtml
+++ b/paludis/repositories/e/ebuild/utils/dohtml
@@ -23,8 +23,8 @@
 
 source ${PALUDIS_EBUILD_DIR}/0/list_functions.bash
 
-if [[ ! -d ${D} ]]; then
-    echo "${0}: \${D} not valid; aborting" >&2
+if [[ ! -d ${!PALUDIS_IMAGE_DIR_VAR} ]]; then
+    echo "${0}: \${${PALUDIS_IMAGE_DIR_VAR}} not valid; aborting" >&2
     exit 247
 fi
 
@@ -93,7 +93,7 @@ install_file() {
 
     [[ -z ${DOCDESTTREE} ]] && DOCDESTTREE="html"
 
-    dir="${D}usr/share/doc/${PF}/${DOCDESTTREE}/${doc_prefix}/${prefix}"
+    dir="${!PALUDIS_IMAGE_DIR_VAR}usr/share/doc/${PF}/${DOCDESTTREE}/${doc_prefix}/${prefix}"
 
     if [[ -f ${path} ]]; then
         ext="$(basename ${path})"
