kdebuild-1 support. Fixes: ticket:500, ticket:523, ticket:524, ticket:526, ticket:528, ticket:530, ticket:531, ticket:532, ticket:533, ticket:534, ticket:535, ticket:536, ticket:537, ticket:538, ticket:539

diff --git a/paludis/repositories/e/ebuild/utils/dosym b/paludis/repositories/e/ebuild/utils/dosym
--- a/paludis/repositories/e/ebuild/utils/dosym
+++ b/paludis/repositories/e/ebuild/utils/dosym
@@ -36,8 +36,14 @@ if [[ ${#} -ne 2 ]]; then
 fi
 
 if [[ ! -d $(dirname "${D}$2") ]]; then
-    ebuild_notice "qa" "$0: target directory $(dirname "${D}$2") does not exist; creating. Please fix the ebuild to create it explicitly."
-    dodir $(dirname $2)
+    if [[ -n "${PALUDIS_DOSYM_NO_MKDIR}" ]] ; then
+        echo "dosym: error: target directory $(dirname "${D}$2" ) does not exist" 1>&2
+        kill -s SIGUSR1 "${EBUILD_KILL_PID}"
+        exit 123
+    else
+        ebuild_notice "qa" "$0: target directory $(dirname "${D}$2") does not exist; creating. Please fix the ebuild to create it explicitly."
+        dodir $(dirname $2)
+    fi
 fi
 
 ln -snf "${1}" "${D}${2}"
