Refactor unpack, add EAPI-dependent suffixes, add .tar.xz and .xz
Also fix some silly bugs and lha retardedness.

diff --git a/paludis/repositories/e/ebuild/utils/unpack b/paludis/repositories/e/ebuild/utils/unpack
--- a/paludis/repositories/e/ebuild/utils/unpack
+++ b/paludis/repositories/e/ebuild/utils/unpack
@@ -36,13 +36,85 @@ assert()
     [[ -z "${_pipestatus//[ 0]/}" ]] || die "$@: $_pipestatus"
 }
 
+unpack_tar() {
+    echo tar xf "${1}" --no-same-owner "${TAR_OPTIONS[@]}" 1>&2
+    tar xf "${1}" --no-same-owner "${TAR_OPTIONS[@]}"
+}
+
+unpack_tar.gz() {
+    echo tar zxf "${1}" --no-same-owner "${TAR_OPTIONS[@]}" 1>&2
+    tar zxf "${1}" --no-same-owner "${TAR_OPTIONS[@]}"
+}
+
+unpack_tar.bz2() {
+    echo tar jxf "${1}" --no-same-owner "${TAR_OPTIONS[@]}" "${UNPACKONLY}" 1>&2
+    tar jxf "${1}" --no-same-owner "${TAR_OPTIONS[@]}" "${UNPACKONLY}"
+}
+
+unpack_zip() {
+    echo unzip -qo "${1}" 1>&2
+    unzip -qo "${1}"
+}
+
+unpack_gz() {
+    echo gzip -dc "${1}" \> "${UNPACKTODIR}/$(basename "${1%.*}" )" 1>&2
+    gzip -dc "${1}" > "${UNPACKTODIR}/$(basename "${1%.*}" )"
+}
+
+unpack_bz2() {
+    echo bzip2 -dc "${1}" \> "${UNPACKTODIR}/$(basename "${1%.*}" )" 1>&2
+    bzip2 -dc "${1}" > "${UNPACKTODIR}/$(basename "${1%.*}" )" || die "Couldn't unpack ${1}"
+}
+
+unpack_rar() {
+    echo unrar x -idq "${1}" 1>&2
+    unrar x -idq "${1}"
+}
+
+unpack_lha() {
+    echo lha xfq "${1}" 1>&2
+    lha xfq "${1}"
+}
+
+unpack_a() {
+    echo ar x "${1}" 1>&2
+    ar x "${1}" 1>&2
+}
+
+unpack_tar.lzma() {
+    echo lzma -dc "${1}" \| tar xf - --no-same-owner "${TAR_OPTIONS[@]}"
+    lzma -dc "${1}" | tar xf - --no-same-owner "${TAR_OPTIONS[@]}"
+    assert "Couldn't unpack ${1}"
+}
+
+unpack_lzma() {
+    echo lzma -dc "${1}" \> "${UNPACKTODIR}/$(basename "${1%.*}" )" 1>&2
+    lzma -dc "${1}" > "${UNPACKTODIR}/$(basename "${1%.*}" )"
+}
+
+unpack_7z() {
+    echo 7z x -y "${1}"
+    7z x -y "${1}"
+}
+
+unpack_tar.xz() {
+    echo xz -dc "${1}" \| tar xf - --no-same-owner "${TAR_OPTIONS[@]}"
+    xz -dc "${1}" | tar xf - --no-same-owner "${TAR_OPTIONS[@]}"
+    assert "Couldn't unpack ${1}"
+}
+
+unpack_xz() {
+    echo xz -dc "${1}" \> "${UNPACKTODIR}/$(basename "${1%.*}" )" 1>&2
+    xz -dc "${1}" > "${UNPACKTODIR}/$(basename "${1%.*}" )"
+}
+
 unpack_one()
 {
-    [[ -z "$1" ]] && die "Bad argument for unpack_one"
-    [[ -e "$1" ]] || die "${1} doesn't exist"
+    [[ -z ${1} ]] && die "Bad argument for unpack_one"
+    [[ -e ${1} ]] || die "${1} doesn't exist"
 
     if [[ -n "${UNPACKONLY}" ]] ; then
-        case "${x}" in
+        case ${1} in
             *.tar.bz2|*.tbz2|*.tbz)
             ;;
 
@@ -52,76 +124,22 @@ unpack_one()
         esac
     fi
 
-    case "${x}" in
-        *.tar)
-            echo tar xf "${1}" --no-same-owner "${TAR_OPTIONS[@]}" 1>&2
-            tar xf "${1}" --no-same-owner "${TAR_OPTIONS[@]}" || die "Couldn't unpack ${1}"
-            ;;
-
-        *.tar.gz|*.tgz|*.tar.Z)
-            echo tar zxf "${1}" --no-same-owner "${TAR_OPTIONS[@]}" 1>&2
-            tar zxf "${1}" --no-same-owner "${TAR_OPTIONS[@]}" || die "Couldn't unpack ${1}"
-            ;;
-
-        *.tar.bz2|*.tbz2|*.tbz)
-            echo tar jxf "${1}" --no-same-owner "${TAR_OPTIONS[@]}" ${UNPACKONLY} 1>&2
-            tar jxf "${1}" --no-same-owner "${TAR_OPTIONS[@]}" ${UNPACKONLY} || die "Couldn't unpack ${1}"
-            ;;
-
-        *.zip|*.ZIP|*.jar)
-            echo unzip -qo "${1}" 1>&2
-            unzip -qo "${1}" || die "Couldn't unpack ${1}"
-            ;;
-
-        *.gz|*.Z|*.z)
-            echo gzip -dc "${1}" > ${UNPACKTODIR}/$(basename "${1%.*}" ) 1>&2
-            gzip -dc "${1}" > ${UNPACKTODIR}/$(basename "${1%.*}" ) || die "Couldn't unpack ${1}"
-            ;;
-
-        *.bz2)
-            echo bzip2 -dc "${1}" > ${UNPACKTODIR}/$(basename "${1%.*}" ) 1>&2
-            bzip2 -dc "${1}" > ${UNPACKTODIR}/$(basename "${1%.*}" ) || die "Couldn't unpack ${1}"
-            ;;
-
-        *.rar|*.RAR)
-            echo unrar x -idq "${1}" 1>&2
-            unrar x -idq "${1}" || die "Couldn't unpack ${1}"
-            ;;
-
-        *.LHa|*.LHA|*.lha|*.lzh)
-            echo lha xqf "${1}" 1>&2
-            lha xqf "${1}" || die "Couldn't unpack ${1}"
-            ;;
-
-        *.a|*.deb)
-            echo ar x "${1}" 1>&2
-            ar x "${1}" 1>&2
-            ;;
-
-        *.tar.lzma)
-            echo lzma -dc "${1}" \| tar xf - --no-same-owner "${TAR_OPTIONS[@]}"
-            lzma -dc "${1}" | tar xf - --no-same-owner "${TAR_OPTIONS[@]}"
-            assert "Couldn't unpack ${1}"
-            ;;
-
-        *.lzma)
-            echo lzma -dc "${1}" > ${UNPACKTODIR}/$(basename "${1%.*}" ) 1>&2
-            lzma -dc "${1}" > ${UNPACKTODIR}/$(basename "${1%.*}" ) || die "Couldn't unpack ${1}"
-            ;;
-
-        *.7z|*.7Z)
-            echo 7z x -y "${1}"
-            7z x -y "${1}" || die "Couldn't unpack ${1}"
-            ;;
-
-        *)
-            if [[ -n "${PALUDIS_UNPACK_UNRECOGNISED_IS_FATAL}" ]] ; then
-                die "Don't know how to unpack ${x}"
-            else
-                echo "Skipping unpack for ${1}"
+    local group split suffix
+    for group in ${PALUDIS_UNPACK_SUFFIXES}; do
+        split=( $(IFS=,; echo ${group} ) )
+        for suffix in ${split[@]}; do
+            if [[ ${1} == *.${suffix} ]]; then
+                unpack_${split[0]} "${1}" || die "Couldn't unpack ${1}"
+                return
             fi
-            ;;
-    esac
+        done
+    done
+
+    if [[ -n "${PALUDIS_UNPACK_UNRECOGNISED_IS_FATAL}" ]] ; then
+        die "Don't know how to unpack ${x}"
+    else
+        echo "Skipping unpack for ${1}"
+    fi
 }
 
 export UNPACKFROMDIR="${!PALUDIS_UNPACK_FROM_VAR}"
