Support the epic piece of fail that is 7z.  From: Maciej Grela
Fixes: ticket:673

diff --git a/paludis/repositories/e/ebuild/utils/unpack b/paludis/repositories/e/ebuild/utils/unpack
--- a/paludis/repositories/e/ebuild/utils/unpack
+++ b/paludis/repositories/e/ebuild/utils/unpack
@@ -109,6 +109,11 @@ unpack_one()
             lzma -dc "${1}" > ${UNPACKTODIR}/$(basename "${1%.*}" ) || die "Couldn't unpack ${1}"
             ;;
 
+        *.7z|*.7Z)
+            echo 7z x -y "${1}"
+            7z x -y "${1}" || die "Couldn't unpack ${1}"
+            ;;
+
         *)
             if [[ -n "${PALUDIS_UNPACK_UNRECOGNISED_IS_FATAL}" ]] ; then
                 die "Don't know how to unpack ${x}"
