EAPI 3 is EAPI 4 now

diff --git a/paludis/repositories/e/ebuild/utils/4/dohard b/paludis/repositories/e/ebuild/utils/4/dohard
--- a/paludis/repositories/e/ebuild/utils/4/dohard
+++ b/paludis/repositories/e/ebuild/utils/4/dohard
@@ -1,11 +1,12 @@
 #!/usr/bin/env bash
 # vim: set sw=4 sts=4 et :
 
-# Copyright (c) 2006, 2007, 2008, 2009 Ciaran McCreesh
+# Copyright (c) 2007, 2008, 2009 Ciaran McCreesh
 #
 # This file is part of the Paludis package manager. Paludis is free software;
 # you can redistribute it and/or modify it under the terms of the GNU General
-# Public License, version 2, as published by the Free Software Foundation.
+# Public License as published by the Free Software Foundation; either version
+# 2 of the License, or (at your option) any later version.
 #
 # Paludis is distributed in the hope that it will be useful, but WITHOUT ANY
 # WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
@@ -16,15 +17,12 @@
 # this program; if not, write to the Free Software Foundation, Inc., 59 Temple
 # Place, Suite 330, Boston, MA  02111-1307  USA
 
-ebuild_notice()
-{
-    [[ -z "${PALUDIS_PIPE_COMMANDS_SUPPORTED}" ]] && return
-    paludis_pipe_command LOG "$EAPI" "$@" >/dev/null
-}
+COLOUR_RED=$'\e[31;01m'
+COLOUR_NORMAL=$'\e[0m'
 
-ebuild_section()
-{
-    echo -ne "${COLOUR_DARK_BLUE}>>>${COLOUR_NORMAL} "
-    echo "$@"
-}
+echo "${COLOUR_RED}!!! Ebuild bug: '$(basename ${0} )' banned in EAPI 3${COLOUR_NORMAL}"
+echo "$(basename ${0} ): making ebuild PID ${EBUILD_KILL_PID} exit with error" 1>&2
+kill -s SIGUSR1 "${EBUILD_KILL_PID}"
+
+exit 123
 
