Allow options to be passed to syncers. From David Leverton. Fixes: ticket:35

diff --git a/ebuild/utils/dounpack b/ebuild/utils/dounpack
--- a/ebuild/utils/dounpack
+++ b/ebuild/utils/dounpack
@@ -34,18 +34,18 @@ unpack_one()
 
     case "${x}" in
         *.tar)
-            echo tar xf "${1}" --no-same-owner 1>&2
-            tar xf "${1}" --no-same-owner || die "Couldn't unpack ${1}"
+            echo tar xf "${1}" --no-same-owner "${TAR_OPTIONS[@]}" 1>&2
+            tar xf "${1}" --no-same-owner "${TAR_OPTIONS[@]}" || die "Couldn't unpack ${1}"
             ;;
 
         *.tar.gz|*.tgz|*.tar.Z)
-            echo tar zxf "${1}" --no-same-owner 1>&2
-            tar zxf "${1}" --no-same-owner || die "Couldn't unpack ${1}"
+            echo tar zxf "${1}" --no-same-owner "${TAR_OPTIONS[@]}" 1>&2
+            tar zxf "${1}" --no-same-owner "${TAR_OPTIONS[@]}" || die "Couldn't unpack ${1}"
             ;;
 
         *.tar.bz2|*.tbz2)
-            echo tar jxf "${1}" --no-same-owner 1>&2
-            tar jxf "${1}" --no-same-owner || die "Couldn't unpack ${1}"
+            echo tar jxf "${1}" --no-same-owner "${TAR_OPTIONS[@]}" 1>&2
+            tar jxf "${1}" --no-same-owner "${TAR_OPTIONS[@]}" || die "Couldn't unpack ${1}"
             ;;
 
         *.zip|*.ZIP|*.jar)
@@ -93,6 +93,12 @@ if [[ "${1}" == "--binary" ]] ; then
     export UNPACKTODIR="${IMAGE}"
     shift
 fi
+
+TAR_OPTIONS=( )
+while [[ "${1}" == --tar-option=* ]] ; do
+    TAR_OPTIONS+=( "${1#*=}" )
+    shift
+done
 
 [[ -z "$@" ]] && die "No arguments given to unpack"
 
