Screw you tar

diff --git a/ebuild/utils/dounpack b/ebuild/utils/dounpack
--- a/ebuild/utils/dounpack
+++ b/ebuild/utils/dounpack
@@ -34,18 +34,18 @@ unpack_one()
 
     case "${x}" in
         *.tar)
-            echo tar --no-same-owner xf "${1}" 1>&2
-            tar --no-same-owner xf "${1}" || die "Couldn't unpack ${1}"
+            echo tar xf "${1}" --no-same-owner 1>&2
+            tar xf "${1}" --no-same-owner || die "Couldn't unpack ${1}"
             ;;
 
         *.tar.gz|*.tgz|*.tar.Z)
-            echo tar --no-same-owner zxf "${1}" 1>&2
-            tar --no-same-owner zxf "${1}" || die "Couldn't unpack ${1}"
+            echo tar zxf "${1}" --no-same-owner 1>&2
+            tar zxf "${1}" --no-same-owner || die "Couldn't unpack ${1}"
             ;;
 
         *.tar.bz2|*.tbz2)
-            echo tar --no-same-owner jxf "${1}" 1>&2
-            tar --no-same-owner jxf "${1}" || die "Couldn't unpack ${1}"
+            echo tar jxf "${1}" --no-same-owner 1>&2
+            tar jxf "${1}" --no-same-owner || die "Couldn't unpack ${1}"
             ;;
 
         *.zip|*.ZIP|*.jar)
