Initial CONFIG_PROTECT support.

diff --git a/ebuild/utils/merge b/ebuild/utils/merge
--- a/ebuild/utils/merge
+++ b/ebuild/utils/merge
@@ -50,6 +50,16 @@ if ! > "${contents}" ; then
     exit 247
 fi
 
+make_cfgpro_filename()
+{
+    local fn="${1}" i=0
+    while [[ -e "${2}/${fn}" ]]; do
+        fn="._cfg$(printf '%.4i' ${i})${1}"
+        (( ++i ))
+    done
+    echo ${fn}
+}
+
 merge_this()
 {
     if [[ ! -d "${1}" ]] || [[ ! -d "${2}" ]] ; then
@@ -107,11 +117,31 @@ merge_this()
                 r=1
             fi
         else
-            if ! cp --remove-destination -pR -- "${f}" "${2}"/ ; then
-                echo "error installing file ${f}"
+            local cfgpro=
+            for c in ${CONFIG_PROTECT}; do
+                if [[ ${2#${top_dst}} == "${c}"/* ]]; then
+                    cfgpro=yes
+                    for cm in ${CONFIG_PROTECT_MASK}; do
+                        if [[ ${2#${top_dst}} == "${cm}"/* ]]; then
+                            cfgpro=
+                        fi
+                    done
+                fi
+            done
+            local fn=${f}
+            if [[ -n ${cfgpro} &&
+                    -e ${2}/${ff} &&
+                    "$(md5sum ${f} |cut -d\  -f 1)" != "$(md5sum ${2}/${ff} |cut -d\  -f 1)" ]]; then
+                fn="${1}/$(make_cfgpro_filename ${ff} ${2})"
+                if [[ ${fn} != ${f} ]]; then
+                    mv "${f}" "${fn}"
+                fi
+            fi
+            if ! cp --remove-destination -pR -- "${fn}" "${2}"/ ; then
+                echo "error installing file ${fn}"
                 r=1
             else
-                if [[ -f "${f}" ]] ; then
+                if [[ -f "${fn}" ]] ; then
                     echo -n "obj ${2#${top_dst}}/${ff} " >> ${contents}
                     echo -n "$(md5sum -- ${2}/${ff} | cut -d' ' -f1 ) " >> ${contents}
                     echo -n "$(stat -c '%Y' -- ${2}/${ff} )" >> ${contents}
